### ISSUE TITLE
404 issue on site login with invalid password

### ISSUE THREAD

**Issue by jjui** [flaviocopes/grav-plugin-shoppingcart#27]
Tested with Antimatter, and latest betas. 

When shoppingcart plugin is active, and when accessing site login with *valid user* but *invalid password*, the error is 404, but not displayed in `error.html.twig`, and error message:
```
[2016-05-13 19:32:42] grav.CRITICAL: Page Not Found - Trace: 
#0 /Users/J/Launch/official_store_beta/user/plugins/shoppingcart/shoppingcart.php(375): Grav\Plugin\ShoppingCart\Controller->execute() 
#1 /Users/J/Launch/official_store_beta/user/plugins/shoppingcart/shoppingcart.php(136): Grav\Plugin\ShoppingcartPlugin->initializeController('login.login', Array) 
#2 [internal function]: Grav\Plugin\ShoppingcartPlugin->onPagesInitialized(Object(RocketTheme\Toolbox\Event\Event), 'onPagesInitiali...', Object(RocketTheme\Toolbox\Event\EventDispatcher))
```
And continued up to `#13`, but think this is most significant.
Any idea why?

**Comment by flaviocopes** [comment]
Right, replicated. Fixed
